### PR TITLE
Solver extension: Improved error logging + fix for multithreading

### PR DESCRIPTION
**Pull request by alma-walmsley**
Better error messages for solver extension error handling.

### CODE REVIEW

**Comment by alma-walmsley** [comment]
Marked as draft for now, I need to fix an issue when running with multithreading

**Comment by APMonitor** [comment]
Let me know when the pull request is ready to merge. It looks like it is still in Draft mode.

**Comment by alma-walmsley** [comment]
I've added the changes now; I'll just get Keegan (who is using this) to verify everything works as expected.

**Comment by alma-walmsley** [comment]
Should be good to go

**Review by APMonitor — APPROVED** [review]

**Comment by APMonitor** [comment]
Thanks for your great work on the solver extension package and on this update for more descriptive error messages.

**Pull request merged**
